name: planetarycomputer
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pystac
  - pystac-client
  - planetary-computer
  - rasterio
  - geopandas
  - matplotlib
  - scikit-image
  - scikit-learn
  - folium
  - leafmap
  - rich
